src/Entity/Oeuvre.php
<?php

namespace App\Entity;

use App\Repository\OeuvreRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=OeuvreRepository::class)
 * @Vich\Uploadable
 */
class Oeuvre
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $titre;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @var File|null
     * @Vich\UploadableField(mapping="oeuvre", fileNameProperty="fileName")
     * @Assert\File(
     *     maxSize = "40M",
     *     mimeTypes = {"image/bmp", "image/png", "image/svg+xml", "image/jpx", "image/jpg", "image/jpeg"},
     *     mimeTypesMessage = "Seul les formats suivant sont acceptés : jpeg/png/svg/bmp"
     * )
     */
    private $file;

    /**
     * @var string|null
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $fileName;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     * @var \DateTimeInterface|null
     */
    private $updatedAt;

    /**
     * @ORM\ManyToOne(targetEntity=YearDirectory::class, inversedBy="oeuvres", cascade={"persist"})
     * @ORM\JoinColumn(onDelete="SET NULL");
     */
    private $year_directory;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $img_position;


    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $year;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $top_position;


    public function __construct()
    {
        $this->setTopPosition(-1);
    }

    public function  __toString()
    {
        return $this->titre;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(?string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getFile()
    {
        return $this->file;
    }


    public function setFile(?File $file = null): void
    {
        $this->file = $file;
        if ($this->file instanceof UploadedFile) {
            $this->updatedAt = new \DateTime('now');
        }
    }

    /**
     * @return string|null
     */
    public function getFileName(): ?string
    {
        return $this->fileName;
    }

    /**
     * @param string|null $fileName
     * @return Oeuvre
     */
    public function setFileName(?string $fileName): Oeuvre
    {
        $this->fileName = $fileName;
        return $this;
    }

    public function getYearDirectory(): ?YearDirectory
    {
        return $this->year_directory;
    }

    public function setYearDirectory(?YearDirectory $year_directory): self
    {
        $this->year_directory = $year_directory;

        return $this;
    }

    public function getImgPosition(): ?int
    {
        return $this->img_position;
    }

    public function setImgPosition(?int $img_position): self
    {
        $this->img_position = $img_position;

        return $this;
    }

    public function getYear(): ?int
    {
        return $this->year;
    }

    public function setYear(?int $year): self
    {
        $this->year = $year;

        return $this;
    }

    public function getTopPosition(): ?int
    {
        return $this->top_position;
    }

    public function setTopPosition(?int $top_position): self
    {
        $this->top_position = $top_position;

        return $this;
    }


}

src/Form/OeuvreType.php
<?php

namespace App\Form;

use App\Entity\Oeuvre;
use App\Entity\YearDirectory;
use FOS\CKEditorBundle\Form\Type\CKEditorType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class OeuvreType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('titre',TextType::class,[
                'error_bubbling' => true,
                'required' => false,
                'label' => 'Titre',
                'label_attr' => ['class'=>'has-text-weight-bold'],
                'row_attr' => ['class'=>'mb-4'],
                'attr' => [
                    'class' => 'input has-text-centered',
                    'placeholder' => 'Ex : Ma belle photo',
                ],
                'help' => 'Nommez cette oeuvre',
                'help_attr' => ['class' => 'help'],
            ])
            ->add('file', FileType::class,[
                'error_bubbling' => true,
                'label' => 'Fichier image',
                'label_attr' => ['class'=>'has-text-weight-bold'],
                'row_attr' => ['class'=>'field is-flex is-flex-direction-column'],
                'attr' => [
                    'class' => 'has-text-centered'
                ],
                'required' => false,
                'help' => 'Types de fichier autorisé : .jpg .png .svg .bmp',
                'help_attr' => ['class' => 'help']
            ])
            ->add('description',CKEditorType::class,[
                'error_bubbling' => true,
                'config' => ['toolbar' => 'config_custom_min'],
                'label' => 'Description',
                'label_attr' => ['class'=>'has-text-weight-bold'],
                'row_attr' => ['class'=>'mb-4'],
                'attr' => [
                    'class' => 'textarea has-text-centered'
                ],
                'required' => false,
                'help' => 'Entrez éventuellement la description de cette oeuvre',
                'help_attr' => ['class' => 'help'],
            ])
            ->add('year',NumberType::class,[
                'required' => false,
                'error_bubbling' => true,
                'label' => 'Année',
                'label_attr' => ['class'=>'has-text-weight-bold'],
                'row_attr' => ['class'=>'mb-4'],
                'attr' => [
                    'class' => 'input has-text-centered',
                    'placeholder' => 'Ex : 2010',
                ],
                'help' => 'Indiquer l\'année de l\'oeuvre',
                'help_attr' => ['class' => 'help'],
            ])
            ->add('year_directory', EntityType::class,[
                'error_bubbling' => true,
                'class' => YearDirectory::class,
                'required' => true,
                'label' => false,
                'placeholder' => false,
                'row_attr' => [
                    'class' => 'select is-fullwidth',
                ],
                'attr' => [
                    'class' => 'has-text-centered has-font-poppins'
                ],
                'choice_label' => 'year',
            ])
            ->add('topPosition',ChoiceType::class,[
                'error_bubbling' => true,
                'label' => false,
                'label_attr' => ['class'=>'has-text-weight-bold'],
                'choices' => [
                    'Sans classement' => 0,
                    '1' => 10,
                    '2' => 9,
                    '3' => 8,
                    '4' => 7,
                    '5' => 6,
                    '6' => 5,
                    '7' => 4,
                    '8' => 3,
                    '9' => 2,
                    '10' => 1,
                ],
                'row_attr' => [
                    'class' => 'select is-fullwidth',
                ],
                'attr' => [
                    'class' => 'has-text-centered has-font-poppins'
                ],
            ])

        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Oeuvre::class,
        ]);
    }
}

src/Controller/OeuvreController.php
<?php

namespace App\Controller;

use App\Entity\Expo;
use App\Entity\Oeuvre;
use App\Entity\TextMenuBurger;
use App\Form\OeuvreType;
use App\Repository\ExpoRepository;
use App\Repository\OeuvreRepository;
use App\Repository\TextMenuBurgerRepository;
use App\Repository\YearDirectoryRepository;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/oeuvre")
 * @IsGranted("ROLE_ADMIN")
 */
class OeuvreController extends AbstractController
{
    private $galeries;
    private $textMenuBurger;
    private $expo;
    public function __construct(YearDirectoryRepository $yearDirectoryRepository, TextMenuBurgerRepository $textMenuBurgerRepository, ExpoRepository $expoRepository, EntityManagerInterface $em)
    {
        $this->galeries = $yearDirectoryRepository->classByYear();
        if (empty($textMenuBurgerRepository->findAll())){
            $newTextMenuBurger = new TextMenuBurger();
            $em->persist($newTextMenuBurger);
            $em->flush();
            $this->textMenuBurger = $textMenuBurgerRepository->findOneBy([]);
        }else{
            $this->textMenuBurger = $textMenuBurgerRepository->findOneBy([]);
        }
        if (empty($expoRepository->findAll())){
            $newExpo = new Expo();
            $em->persist($newExpo);
            $em->flush();
            $this->expo = $expoRepository->findOneBy([]);
        }else{
            $this->expo = $expoRepository->findOneBy([]);
        }
    }

    /**
     * @Route("/", name="oeuvre_index", methods={"GET"})
     */
    public function index(OeuvreRepository $oeuvreRepository, YearDirectoryRepository $yearDirectoryRepository): Response
    {
        return $this->render('oeuvre/index.html.twig', [
            'all_galeries' => $yearDirectoryRepository->findAll(),
            'oeuvres' => $oeuvreRepository->classByAnnee(),
            'galeries' => $this->galeries,
            'text_menu_burger' => $this->textMenuBurger,
            'expo' => $this->expo,
        ]);
    }

    /**
     * @Route("/new", name="oeuvre_new", methods={"GET","POST"})
     */
    public function new(Request $request, OeuvreRepository $oeuvreRepository): Response
    {
        $oeuvre = new Oeuvre();
        $form = $this->createForm(OeuvreType::class, $oeuvre);
        $form->handleRequest($request);
        $nb_oeuvre = count($oeuvreRepository->findAll()) + 1;

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $oeuvre->setImgPosition($nb_oeuvre);
            $entityManager->persist($oeuvre);
            $entityManager->flush();
            $msg = 'L\'oeuvre à bien été ajoutée';
            $this->addFlash('success', $msg);
            return $this->redirectToRoute('oeuvre_index');
        }

        return $this->render('oeuvre/new.html.twig', [
            'oeuvre' => $oeuvre,
            'form' => $form->createView(),
            'galeries' => $this->galeries,
            'text_menu_burger' => $this->textMenuBurger,
            'expo' => $this->expo,
        ]);
    }

    /**
     * @Route("/{id}", name="oeuvre_show", methods={"GET"})
     */
    public function show(Oeuvre $oeuvre): Response
    {
        return $this->render('oeuvre/show.html.twig', [
            'oeuvre' => $oeuvre,
            'galeries' => $this->galeries,
            'text_menu_burger' => $this->textMenuBurger,
            'expo' => $this->expo,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="oeuvre_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Oeuvre $oeuvre): Response
    {
        $form = $this->createForm(OeuvreType::class, $oeuvre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();
            $msg = 'L\'oeuvre <b>' . $oeuvre->getId() . '</b> à bien été modifiée';
            $this->addFlash('success', $msg);
                return $this->redirectToRoute('oeuvre_index');
        }

        return $this->render('oeuvre/edit.html.twig', [
            'oeuvre' => $oeuvre,
            'form' => $form->createView(),
            'galeries' => $this->galeries,
            'text_menu_burger' => $this->textMenuBurger,
            'expo' => $this->expo,
        ]);
    }

    /**
     * @Route("/{id}", name="oeuvre_delete", methods={"POST"})
     */
    public function delete(Request $request, Oeuvre $oeuvre): Response
    {
        if ($this->isCsrfTokenValid('delete'.$oeuvre->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            if ($oeuvre->getTitre() != null){
                $oeuvreName = $oeuvre->getTitre();
            }else{
                $oeuvreName = $oeuvre->getId();
            }
            $entityManager->remove($oeuvre);
            $entityManager->flush();
        }
        $msg = 'L\'oeuvre <b>' . $oeuvreName . '</b> à été supprimée';
        $this->addFlash('warning', $msg);
        return $this->redirectToRoute('oeuvre_index');
    }
}

templates/oeuvre/_delete_form.html.twig
<form class="" method="post" action="{{ path('oeuvre_delete', {'id': oeuvre.id}) }}" onsubmit="return confirm('êtes-vous sur de vouloir supprimer cette oeuvre?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ oeuvre.id) }}">
    <button class="button is-small is-danger has-font-poppins">Supprimer</button>
</form>

templates/oeuvre/_form.html.twig
{{ form_start(form, {'attr': {'class':'column has-text-centered'}}) }}
    {{ form_row(form.year) }}
    <div class="field">
        <div class="label has-text-weight-bold">Galerie</div>
        {{ form_row(form.year_directory) }}
        <div class="help">
            Selectionnez une galerie à cette oeuvre
        </div>
    </div>
    <div class="field">
        <div class="label has-text-weight-bold">Top position</div>
        {{ form_row(form.topPosition) }}
        <div class="help">
            Indiquer la position de la peinture dans le top 10, (présent en page d'accueil)
        </div>
    </div>
    {{ form_row(form.titre) }}
    {{ form_row(form.file) }}
    {% if oeuvre.fileName %}
        <div class="is-flex is-flex-direction-column is-justify-content-center is-align-items-center field">
            <figure class="is-relative">
                <img class="has-max-height-40vh" src="{{ asset('/images/oeuvres/' ~ oeuvre.fileName )}}" alt="{{ oeuvre.titre }}" title="{{ oeuvre.fileName }}">
            </figure>
            <span> <b>Fichier actuel</b> : {{ oeuvre.fileName }}</span>
        </div>
    {% endif %}

    {{ form_row(form.description) }}

    <button class="button is-info is-outlined is-small has-font-poppins">Valider</button>

{{ form_end(form) }}

templates/oeuvre/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier l'Oeuvre{% endblock %}

{% block body %}
<div class="container is-flex is-flex-direction-column is-justify-content-center is-align-items-center py-6">
    <div class="column is-full is-flex is-justify-content-start">
        <a class="button is-small is-dark" href="{{ path('oeuvre_index') }}">Retour à la liste des oeuvres</a>
    </div>

    <h1 class="title">Modifier l'oeuvre</h1>

    {{ include('oeuvre/_form.html.twig', {'button_label': 'Update'}) }}

    {{ include('oeuvre/_delete_form.html.twig') }}
</div>
{% endblock %}

templates/oeuvre/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gestion des oeuvres{% endblock %}

{% block body %}

    <div class="container px-4 py-6">

        <h1 class="title">Gestion des oeuvres</h1>

        <div class="column">
            <span class="help">Filtre :</span>
            <div class="tags">
                {% for galerie in all_galeries %}
                    {% if galerie %}
                        <div class="button tag is-small is-dark is-active" onclick="filtreByGalery(this,{{ galerie.id|raw }})">{{ galerie.year }}</div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>

        <div class="column">
            <a class="button is-small is-dark" href="{{ path('oeuvre_new') }}">Ajouter une oeuvre</a>
        </div>

        <div class="table-wrapper-touch">
            <table class="table" style="margin: auto">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Titre</th>
                    <th>Année</th>
                    <th>Galerie</th>
                    <th class="is-hidden-touch">Fichier image</th>
                    <th>Gestion</th>
                </tr>
                </thead>
                <tbody>
                {% for oeuvre in oeuvres %}
                    {% if oeuvre %}
                    <tr class="{% if oeuvre.yearDirectory %}{{ oeuvre.yearDirectory.id|raw }}{% endif %}">
                        <td>
                            <span class="help">
                                {{ oeuvre.id }}
                            </span>
                        </td>
                        <td>{{ oeuvre.titre }}</td>
                        <td>{{ oeuvre.year }}</td>
                        <td>
                            {% if oeuvre.yearDirectory %}
                                <a href="{{ path('gallery_year', {'id_gallery': oeuvre.yearDirectory.id }) }}" title="Se rendre à la galerie {{ oeuvre.yearDirectory }}">{{ oeuvre.yearDirectory }}</a>
                            {% else %}
                                <span class="is-italic has-text-weight-light">(Vide)</span>
                            {% endif %}
                        </td>
                        <td class="has-text-centered is-relative is-hidden-touch">
                            {% if oeuvre.fileName %}
                                <div class="">
                                    <img style="bottom: 100%;left: 0" class="is-hidden is-absolute has-max-height-20vh has-border-dark-2px" src="{{ asset('/images/oeuvres/' ~ oeuvre.fileName ) | imagine_filter('vignette') }}" alt="{{ oeuvre.titre }}" title="{{ oeuvre.fileName }}">
                                    <span class="icon has-text-dark is-hoverable-help-cursor" onmouseenter="showPrevOnHover(this)" onmouseleave="hidePrevOnHover(this)">
                                    <i class="fas fa-lg fa-eye"></i>
                                </span>
                                </div>
                            {% else %}
                                <span class="has-text-weight-light is-italic is-hoverable-help-cursor" title="Sans fichier image">(Vide)</span>
                            {% endif %}
                        </td>
                        <td>
                            <div class="is-flex is-justify-content-space-between is-align-items-center">
                                <a href="{{ path('oeuvre_show', {'id': oeuvre.id}) }}" title="Voir les détails de cette oeuvre">
                                <span class="icon has-text-dark">
                                    <i class="fas fa-lg fa-search"></i>
                                </span>
                                </a>
                                <a href="{{ path('oeuvre_edit', {'id': oeuvre.id}) }}" title="Modifier cette oeuvre">
                                <span class="icon has-text-dark">
                                    <i class="fas fa-lg fa-edit"></i>
                                </span>
                                </a>
                            </div>
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="7">Aucune oeuvres trouvées</td>
                    </tr>
                    {% endif %}
                {% endfor %}
                </tbody>
            </table>
        </div>

    </div>

{% endblock %}

templates/oeuvre/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle Oeuvre{% endblock %}

{% block body %}
<div class="container is-flex is-flex-direction-column is-justify-content-center is-align-items-center py-6">
    <div class="column is-full is-flex is-justify-content-start">
        <a class="button is-small is-dark" href="{{ path('oeuvre_index') }}">Retour à la liste des oeuvres</a>
    </div>

    <h1 class="title">Ajouter une Oeuvre</h1>

    {{ include('oeuvre/_form.html.twig') }}

</div>
{% endblock %}

templates/oeuvre/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Oeuvre{% endblock %}

{% block body %}

<div class="container is-flex is-flex-direction-column is-justify-content-center is-align-items-center py-6">

    <div class="column is-full is-flex is-justify-content-start">
        <a class="button is-small is-dark" href="{{ path('oeuvre_index') }}">Retour à la liste des oeuvres</a>
    </div>

    <div class="column {% if not oeuvre.fileName %}is-flex is-flex-direction-column is-justify-content-center{% endif %} has-text-centered has-border-thin has-border-radius-3px is-relative is-full-touch mb-5 mx-3 has-background-white-bis is-full-desktop">

        {% if oeuvre.fileName %}
            <div class="column is-flex is-justify-content-center">
                <img class="has-max-height-50vh" src="{{ asset('/images/oeuvres/') }}{{ oeuvre.fileName }}" alt="{{ oeuvre.fileName }}" title="{{ oeuvre.titre }}">
            </div>
        {% endif %}

        <h2 class="subtitle has-text-centered has-text-weight-bold has-font-playfair">
            {{ oeuvre.titre }}
        </h2>

        <div class="is-flex is-flex-direction-column is-justify-content-center is-align-items-center has-max-width-500px has-font-playfair  mb-4" style="margin: 0 auto">
            {{ oeuvre.description|raw }}
        </div>

        <h3 class="subtitle has-text-weight-light is-4 is-flex is-flex-direction-column is-justify-content-center is-align-items-center has-max-width-500px" style="margin: 0 auto">
            Gallerie associée :
            {% if oeuvre.yearDirectory is empty %}
                <span class="has-text-weight-light is-italic">Aucune</span>
            {% else %}
                <span class="has-text-weight-bold">{{ oeuvre.yearDirectory }}</span>
            {% endif %}
        </h3>

    </div>

{#    <img class="" src="{{ asset('images/oeuvres/' ~ oeuvre.fileName) | imagine_filter('small') }}" alt="{{ oeuvre.fileName }}">#}

{#    <h1>Oeuvre : {{ oeuvre.titre }}</h1>#}

{#    <table class="table">#}
{#        <tbody>#}
{#            <tr>#}
{#                <th>Id</th>#}
{#                <td>{{ oeuvre.id }}</td>#}
{#            </tr>#}
{#            <tr>#}
{#                <th>Titre</th>#}
{#                <td>{{ oeuvre.titre }}</td>#}
{#            </tr>#}
{#            <tr>#}
{#                <th>Description</th>#}
{#                <td>{{ oeuvre.description|raw }}</td>#}
{#            </tr>#}
{#            <tr>#}
{#                <th>Fichier</th>#}
{#                <td>{{ oeuvre.fileName }}</td>#}
{#            </tr>#}
{#            <tr>#}
{#                <th>Annee</th>#}
{#                <td>{{ oeuvre.yearDirectory }}</td>#}
{#            </tr>#}
{#        </tbody>#}
{#    </table>#}

    <div class="column is-full is-flex is-justify-content-space-evenly">
        <a class="button is-small is-dark is-outlined mr-5" href="{{ path('oeuvre_edit', {'id': oeuvre.id}) }}">Modifier</a>

        {{ include('oeuvre/_delete_form.html.twig') }}
    </div>

</div>
{% endblock %}