src/Entity/Oeuvre.php
<?php

namespace App\Entity;

use App\Repository\OeuvreRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=OeuvreRepository::class)
 * @Vich\Uploadable
 */
class Oeuvre
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $titre;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @var File|null
     * @Vich\UploadableField(mapping="oeuvre", fileNameProperty="fileName")
     * @Assert\File(
     *     maxSize = "40M",
     *     mimeTypes = {"image/bmp", "image/png", "image/svg+xml", "image/jpx", "image/jpg", "image/jpeg"},
     *     mimeTypesMessage = "Seul les formats suivant sont acceptés : jpeg/png/svg/bmp"
     * )
     */
    private $file;

    /**
     * @var string|null
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $fileName;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     * @var \DateTimeInterface|null
     */
    private $updatedAt;

    /**
     * @ORM\ManyToOne(targetEntity=YearDirectory::class, inversedBy="oeuvres", cascade={"persist"})
     * @ORM\JoinColumn(onDelete="SET NULL");
     */
    private $year_directory;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $img_position;


    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $year;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $top_position;


    public function __construct()
    {
        $this->setTopPosition(-1);
    }

    public function  __toString()
    {
        return $this->titre;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(?string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getFile()
    {
        return $this->file;
    }


    public function setFile(?File $file = null): void
    {
        $this->file = $file;
        if ($this->file instanceof UploadedFile) {
            $this->updatedAt = new \DateTime('now');
        }
    }

    /**
     * @return string|null
     */
    public function getFileName(): ?string
    {
        return $this->fileName;
    }

    /**
     * @param string|null $fileName
     * @return Oeuvre
     */
    public function setFileName(?string $fileName): Oeuvre
    {
        $this->fileName = $fileName;
        return $this;
    }

    public function getYearDirectory(): ?YearDirectory
    {
        return $this->year_directory;
    }

    public function setYearDirectory(?YearDirectory $year_directory): self
    {
        $this->year_directory = $year_directory;

        return $this;
    }

    public function getImgPosition(): ?int
    {
        return $this->img_position;
    }

    public function setImgPosition(?int $img_position): self
    {
        $this->img_position = $img_position;

        return $this;
    }

    public function getYear(): ?int
    {
        return $this->year;
    }

    public function setYear(?int $year): self
    {
        $this->year = $year;

        return $this;
    }

    public function getTopPosition(): ?int
    {
        return $this->top_position;
    }

    public function setTopPosition(?int $top_position): self
    {
        $this->top_position = $top_position;

        return $this;
    }


}

src/Entity/YearDirectory.php
<?php

namespace App\Entity;

use App\Repository\YearDirectoryRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass=YearDirectoryRepository::class)
 * @Vich\Uploadable
 * @UniqueEntity(
 *     fields={"year"},
 *     message="Une galerie avec cette année existe déjà"
 * )
 */
class YearDirectory
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $title;

    /**
     * @ORM\OneToMany(targetEntity=Oeuvre::class, mappedBy="year_directory")
     */
    private $oeuvres;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $year;

    /**
     * @var File|null
     * @Vich\UploadableField(mapping="year_directory_img", fileNameProperty="fileName")
     * @Assert\File(
     *     maxSize = "40M",
     *     mimeTypes = {"image/bmp", "image/png", "image/svg+xml", "image/jpx", "image/jpg", "image/jpeg"},
     *     mimeTypesMessage = "Seul les formats suivant sont acceptés : jpeg/png/svg/bmp"
     * )
     */
    private $file;

    /**
     * @var string|null
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $fileName;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     * @var \DateTimeInterface|null
     */
    private $updatedAt;

    /**
     * @ORM\Column(type="integer")
     */
    private $year_start;

    /**
     * @ORM\Column(type="integer")
     */
    private $year_end;

    public function __construct()
    {
        $this->oeuvres = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->getYear();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    /**
     * @return Collection|Oeuvre[]
     */
    public function getOeuvres(): Collection
    {
        return $this->oeuvres;
    }

    public function addOeuvre(Oeuvre $oeuvre): self
    {
        if (!$this->oeuvres->contains($oeuvre)) {
            $this->oeuvres[] = $oeuvre;
            $oeuvre->setYearDirectory($this);
        }

        return $this;
    }

    public function removeOeuvre(Oeuvre $oeuvre): self
    {
        if ($this->oeuvres->removeElement($oeuvre)) {
            // set the owning side to null (unless already changed)
            if ($oeuvre->getYearDirectory() === $this) {
                $oeuvre->setYearDirectory(null);
            }
        }

        return $this;
    }

    public function getYear(): ?string
    {
        return $this->year;
    }

    public function setYear(?string $year): self
    {
        $this->year = $year;

        return $this;
    }

    public function getFile()
    {
        return $this->file;
    }


    public function setFile(?File $file = null): void
    {
        $this->file = $file;
        if ($this->file instanceof UploadedFile) {
            $this->updatedAt = new \DateTime('now');
        }
    }

    /**
     * @return string|null
     */
    public function getFileName(): ?string
    {
        return $this->fileName;
    }

    /**
     * @param string|null $fileName
     * @return YearDirectory
     */
    public function setFileName(?string $fileName): YearDirectory
    {
        $this->fileName = $fileName;
        return $this;
    }

    public function getYearStart(): ?int
    {
        return $this->year_start;
    }

    public function setYearStart(int $year_start): self
    {
        $this->year_start = $year_start;

        return $this;
    }

    public function getYearEnd(): ?int
    {
        return $this->year_end;
    }

    public function setYearEnd(int $year_end): self
    {
        $this->year_end = $year_end;

        return $this;
    }
}

src/Controller/YearDirectoryController.php
<?php

namespace App\Controller;

use App\Entity\Expo;
use App\Entity\TextMenuBurger;
use App\Entity\YearDirectory;
use App\Form\YearDirectoryType;
use App\Repository\ExpoRepository;
use App\Repository\OeuvreRepository;
use App\Repository\TextMenuBurgerRepository;
use App\Repository\YearDirectoryRepository;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/year/directory")
 * @IsGranted("ROLE_ADMIN")
 */
class YearDirectoryController extends AbstractController
{

    private $galeries;
    private $textMenuBurger;
    private $expo;
    public function __construct(YearDirectoryRepository $yearDirectoryRepository, TextMenuBurgerRepository $textMenuBurgerRepository, ExpoRepository $expoRepository, EntityManagerInterface $em)
    {
        $this->galeries = $yearDirectoryRepository->classByYear();
        if (empty($textMenuBurgerRepository->findAll())){
            $newTextMenuBurger = new TextMenuBurger();
            $em->persist($newTextMenuBurger);
            $em->flush();
            $this->textMenuBurger = $textMenuBurgerRepository->findOneBy([]);
        }else{
            $this->textMenuBurger = $textMenuBurgerRepository->findOneBy([]);
        }
        if (empty($expoRepository->findAll())){
            $newExpo = new Expo();
            $em->persist($newExpo);
            $em->flush();
            $this->expo = $expoRepository->findOneBy([]);
        }else{
            $this->expo = $expoRepository->findOneBy([]);
        }
    }

    /**
     * @Route("/", name="year_directory_index", methods={"GET"})
     */
    public function index(YearDirectoryRepository $yearDirectoryRepository): Response
    {
        return $this->render('year_directory/index.html.twig', [
            'year_directories' => $yearDirectoryRepository->findAll(),
            'galeries' => $this->galeries,
            'text_menu_burger' => $this->textMenuBurger,
            'expo' => $this->expo,
        ]);
    }

    /**
     * @Route("/new", name="year_directory_new", methods={"GET","POST"})
     */
    public function new(Request $request, OeuvreRepository $oeuvreRepository): Response
    {
        $oeuvres = $oeuvreRepository->findAll();
        $yearDirectory = new YearDirectory();
        $form = $this->createForm(YearDirectoryType::class, $yearDirectory);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($yearDirectory);
            $entityManager->flush();
            $msg = 'La galerie à bien été créée';
            $this->addFlash('success', $msg);
            return $this->redirectToRoute('year_directory_index');
        }

        return $this->render('year_directory/new.html.twig', [
            'year_directory' => $yearDirectory,
            'form' => $form->createView(),
            'galeries' => $this->galeries,
            'text_menu_burger' => $this->textMenuBurger,
            'oeuvres' => $oeuvres,
            'expo' => $this->expo,
        ]);
    }

    /**
     * @Route("/{id}", name="year_directory_show", methods={"GET"})
     */
    public function show(YearDirectory $yearDirectory): Response
    {
        return $this->render('year_directory/show.html.twig', [
            'year_directory' => $yearDirectory,
            'galeries' => $this->galeries,
            'text_menu_burger' => $this->textMenuBurger,
            'expo' => $this->expo,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="year_directory_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, YearDirectory $yearDirectory, OeuvreRepository $oeuvreRepository): Response
    {
        $oeuvres = $oeuvreRepository->findAll();
        $form = $this->createForm(YearDirectoryType::class, $yearDirectory);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $msg = 'La galerie à bien été modifiée';
            $this->addFlash('success', $msg);
            $this->getDoctrine()->getManager()->flush();
        }

        return $this->render('year_directory/edit.html.twig', [
            'year_directory' => $yearDirectory,
            'form' => $form->createView(),
            'galeries' => $this->galeries,
            'text_menu_burger' => $this->textMenuBurger,
            'oeuvres' => $oeuvres,
            'expo' => $this->expo,
        ]);
    }

    /**
     * @Route("/{id_gallery}/add-{id_oeuvre}", name="year_directory_add_oeuvre")
     */
    public function addOeuvreInGallery(YearDirectoryRepository $yearDirectoryRepository,OeuvreRepository $oeuvreRepository, $id_gallery, $id_oeuvre, EntityManagerInterface $em): Response
    {
        $oeuvre = $oeuvreRepository->find($id_oeuvre);
        $gallery = $yearDirectoryRepository->find($id_gallery);

        if ($gallery->getOeuvres()->contains($oeuvre)){
            $gallery->removeOeuvre($oeuvre);
            $msg = 'L\'oeuvre <b>' . $oeuvre->getTitre() . '</b> à été retirée de cette galerie';
            $type = 'warning';
        }else{
            $gallery->addOeuvre($oeuvre);
            $msg = 'L\'oeuvre <b>' . $oeuvre->getTitre() . '</b> à été ajoutée à cette galerie';
            $type = 'info';
        }
        $em->persist($gallery);
        $em->flush();

        return $this->json([
            'id' => $id_gallery,
            'flash_message' => $msg,
            'type' => $type,
        ]);
    }

    /**
     * @Route("/{id}", name="year_directory_delete", methods={"POST"})
     */
    public function delete(Request $request, YearDirectory $yearDirectory): Response
    {
        if ($this->isCsrfTokenValid('delete'.$yearDirectory->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($yearDirectory);
            $entityManager->flush();
        }
        $msg = 'La galerie à bien été supprimée';
        $this->addFlash('warning', $msg);
        return $this->redirectToRoute('year_directory_index');
    }

    /**
     * @Route("/{id}/del-img", name="year_directory_delete_img")
     */
    public function deleteImg(YearDirectory $yearDirectory, $id): Response
    {
        $entityManager = $this->getDoctrine()->getManager();
        $yearDirectory->setFileName(null);
        $entityManager->persist($yearDirectory);
        $entityManager->flush();
        $msg = 'L\'image de couverture de la galerie à bien été supprimée';
        $this->addFlash('warning', $msg);
        return $this->redirectToRoute('year_directory_edit',[
            'id' => $id,
        ]);
    }
}

templates/year_directory/_delete_form.html.twig
<form method="post" action="{{ path('year_directory_delete', {'id': year_directory.id}) }}" onsubmit="return confirm('êtes-vous sur de vouloir supprimer cette galerie ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ year_directory.id) }}">
    <button class="button is-small is-danger has-font-poppins">Supprimer</button>
</form>

templates/year_directory/_form.html.twig
    {{ form_start(form, {'attr': {'class':'column has-text-centered'}}) }}
    {{ form_row(form.year) }}
    <div class="field">
        <div class="field mb-0 has-addons">
            <div class="is-flex">
                {{ form_row(form.yearStart) }}
                {{ form_row(form.yearEnd) }}
            </div>
        </div>
        <span class="help">Indiquez la tranche annuelle de la galerie</span>
    </div>


    {{ form_widget(form) }}
{#    {% if year_directory.fileName %}#}
{#        <div class="is-flex is-flex-direction-column is-justify-content-center is-align-items-center field">#}
{#            <figure class="is-relative">#}
{#                <a href="{{ path('year_directory_delete_img', {'id': year_directory.id}) }}" class="delete is-medium is-absolute is-top-075rem is-right-075rem" title="Supprimer l'image de la galerie" onclick="return confirm('Êtes-vous sur de vouloir supprimer cette l\'image de couverture de la galerie ?');"></a>#}
{#                <img class="" src="{{ asset('/images/years_directory_img/' ~ year_directory.filename ) | imagine_filter('small') }}" alt="{{ year_directory.title }}" title="{{ year_directory.fileName }}">#}
{#            </figure>#}
{#        </div>#}
{#    {% else %}#}
{#        <div class="column has-text-centered">#}
{#            <h3 class="subtitle">#}
{#                Aucun fichier image uploadé pour cette galerie#}
{#            </h3>#}
{#            <div class="help pb-6 text-icon">#}
{#                <span class="icon">#}
{#                    <i class="fas fa-lg fa-info-circle"></i>#}
{#                </span>#}
{#                Si aucun fichier image n'a été uploader, l'image de la première oeuvre sera affichée en couverture#}
{#            </div>#}
{#        </div>#}
{#    {% endif %}#}
    <div class="field">
        <button class="button is-info is-outlined is-small has-font-poppins">Valider</button>
    </div>
    {{ form_end(form) }}

templates/year_directory/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier la galerie{% endblock %}

{% block body %}
<div class="container is-flex is-flex-direction-column is-justify-content-center is-align-items-center py-6">
    <div class="column buttons is-full is-flex is-justify-content-start">
        <a class="button is-small is-dark" href="{{ path('year_directory_index') }}">Retour à la liste des galeries</a>
        <a class="button is-small is-dark" href="{{ path('gallery_year', {'id_gallery': year_directory.id}) }}">Parcourir cette galerie</a>
    </div>

    <h1 class="title">Modifier la galerie</h1>

    {{ include('year_directory/_form.html.twig', {'button_label': 'Update'}) }}

    {{ include('year_directory/_delete_form.html.twig') }}
</div>

    <h3 class="subtitle has-text-centered has-text-weight-bold">Selectionner les oeuvres de cette galerie</h3>
    <div class="columns is-multiline px-6 is-flex is-justify-content-center">
        {% for oeuvre in oeuvres %}
            {% if oeuvre.fileName %}
                <a class="has-transition-5-ms column is-relative is-flex is-flex-direction-column is-justify-content-space-evenly is-align-items-center is-one-fifth is-full-mobile has-text-centered add-remove-oeuvre-ajax {% if oeuvre.yearDirectory == year_directory %} opacity-1{% else %} opacity-05{% endif %}" href="{{ path('year_directory_add_oeuvre', {'id_gallery': year_directory.id, 'id_oeuvre': oeuvre.id }) }}">

                        <span class="icon tag is-light is-medium is-absolute is-top-075rem is-right-075rem has-text-info {% if oeuvre.yearDirectory != year_directory %}is-hidden{% endif %}">
                            <i class="fas fa-lg fa-check-circle"></i>
                        </span>

                    <img src="{{ asset('images/oeuvres/' ~ oeuvre.fileName) | imagine_filter('small') }}" alt="">
                    <div class="tag">
                        {{ oeuvre.titre }}
                    </div>
                </a>
            {% endif %}
        {% endfor %}
    </div>

{% endblock %}

templates/year_directory/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gestion des galeries{% endblock %}

{% block body %}
<div class="container px-4 py-6">

    <h1 class="title">Gestion des galeries</h1>

    <a class="button is-small is-dark" href="{{ path('year_directory_new') }}">Ajouter une galerie</a>

    <div class="table-wrapper-touch">
        <table class="table" style="margin: auto">
            <thead>
            <tr>
                <th>Titre</th>
                <th>Description</th>
{#                <th class="is-hidden-touch">Couverture</th>#}
                <th>Gestion</th>
            </tr>
            </thead>
            <tbody>
            {% for year_directory in year_directories %}
                <tr>
                    <td>
                        {{ year_directory.year }}
                    </td>

                    <td>
                        {{ year_directory.title }}
                    </td>

{#                    <td class="has-text-centered is-relative is-hidden-touch">#}
{#                        {% if year_directory.fileName %}#}
{#                            <div class="">#}
{#                                <img style="bottom: 100%;left: 0" class="is-hidden is-absolute has-max-height-20vh has-border-white-5px" src="{{ asset('/images/years_directory_img/' ~ year_directory.filename ) | imagine_filter('vignette') }}" alt="{{ year_directory.title }}" title="{{ year_directory.fileName }}">#}
{#                                <span class="icon has-text-dark is-hoverable-help-cursor" onmouseenter="showPrevOnHover(this)" onmouseleave="hidePrevOnHover(this)">#}
{#                                <i class="fas fa-lg fa-eye"></i>#}
{#                            </span>#}
{#                            </div>#}
{#                        {% else %}#}
{#                            <span class="has-text-weight-light is-italic is-hoverable-help-cursor" title="L'image de la première oeuvre de cette galerie sera donc affichée">(Vide)</span>#}
{#                        {% endif %}#}
{#                    </td>#}

                    <td>
                        <div class="is-flex is-justify-content-space-evenly is-align-items-center">
                            <a href="{{ path('year_directory_show', {'id': year_directory.id}) }}" title="Voir les détails de cette galerie">
                            <span class="icon has-text-dark">
                                <i class="fas fa-lg fa-search"></i>
                            </span>
                            </a>
                            <a href="{{ path('year_directory_edit', {'id': year_directory.id}) }}" title="Modifier cette galerie">
                            <span class="icon has-text-dark">
                                <i class="fas fa-lg fa-edit"></i>
                            </span>
                            </a>
                        </div>
                    </td>

                </tr>
            {% else %}
                <tr>
                    <td colspan="6">Aucune galeries trouvées</td>
                </tr>
            {% endfor %}
            </tbody>
            <tfoot>
            <tr>
                <th>Titre</th>
                <th>Année</th>
{#                <th>Couverture</th>#}
                <th>Gestion</th>
            </tr>
            </tfoot>
        </table>
    </div>
</div>
{% endblock %}

templates/year_directory/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle galerie{% endblock %}

{% block body %}
<div class="container is-flex is-flex-direction-column is-justify-content-center is-align-items-center py-6">
    <div class="column is-full is-flex is-justify-content-start">
        <a class="button is-small is-dark" href="{{ path('year_directory_index') }}">Retour à la liste des galeries</a>
    </div>

    <h1 class="title">Créer une nouvelle galerie</h1>

    {{ include('year_directory/_form.html.twig') }}

</div>

{#    <h3 class="subtitle has-text-centered has-text-weight-bold">Selectionner les oeuvres de cette galerie</h3>#}
{#    <div class="columns is-multiline px-6 is-flex is-justify-content-center">#}
{#        {% for oeuvre in oeuvres %}#}
{#            {% if oeuvre.fileName %}#}
{#                <a href="" class="column is-flex is-flex-direction-column is-justify-content-space-evenly is-align-items-center is-one-fifth is-full-mobile has-text-centered opacity-05">#}
{#                    <img src="{{ asset('images/oeuvres/' ~ oeuvre.fileName) | imagine_filter('small') }}" alt="">#}
{#                    <div class="tag">#}
{#                        {{ oeuvre.titre }}#}
{#                    </div>#}
{#                </a>#}
{#            {% endif %}#}
{#        {% endfor %}#}
{#    </div>#}

{% endblock %}

templates/year_directory/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Galerie{% endblock %}

{% block body %}
<div class="container is-flex is-flex-direction-column is-justify-content-center is-align-items-center py-6">

    <div class="column buttons is-full is-flex is-justify-content-start">
        <a class="button is-small is-dark" href="{{ path('year_directory_index') }}">Retour à la liste des galeries</a>
        <a class="button is-small is-dark" href="{{ path('gallery_year', {'id_gallery': year_directory.id}) }}">Parcourir cette galerie</a>
    </div>

    <h1 class="title"><span class="has-text-weight-light">Galerie</span> {{ year_directory.year }}</h1>

{#    {% if year_directory.fileName %}#}
{#        <img class="" src="{{ asset('images/years_directory_img/' ~ year_directory.filename ) | imagine_filter('small') }}" alt="{{ year_directory.title }}" title="{{ year_directory.fileName }}">#}
{#    {% else %}#}

{#        {% if year_directory.oeuvres is not empty and year_directory.oeuvres[0].filename %}#}
{#            <div class="column is-flex is-justify-content-center is-align-items-center">#}
{#                <img class="has-max-height-40vh has-border-white-5px" src="{{ asset('/images/oeuvres/' ~ year_directory.oeuvres[0].filename ) }}" alt="Couverture de galerie manquante" title="{{ year_directory.title }}">#}
{#            </div>#}
{#        {% endif %}#}

{#        <div class="column has-text-centered">#}
{#            <h3 class="subtitle">#}
{#                Aucun fichier image uploadé pour cette galerie#}
{#            </h3>#}
{#            <div class="help pb-6 text-icon">#}
{#                <span class="icon">#}
{#                    <i class="fas fa-lg fa-info-circle"></i>#}
{#                </span>#}
{#                Si aucun fichier image n'a été uploader, l'image de la première oeuvre sera affichée en couverture#}
{#            </div>#}
{#        </div>#}
{#    {% endif %}#}

    <table class="table">
        <tbody>
            <tr>
                <th>Titre</th>
                <td>{{ year_directory.year }}</td>
            </tr>
            <tr>
                <th>Sous-titre</th>
                <td>{{ year_directory.title }}</td>
            </tr>
{#            <tr>#}
{#                <th>Fichier</th>#}
{#                <td>{{ year_directory.fileName }}</td>#}
{#            </tr>#}
        </tbody>
    </table>

    <div class="columns is-multiline is-flex is-justify-content-center">
        {% for oeuvre in year_directory.oeuvres %}
            {% if oeuvre.fileName %}

                <div class="modal opacity-0 has-transition-5-ms">
                    <div class="modal-background" onclick="closeModal(this)"></div>
                    <figure class="z-index-more-1 is-flex-direction-column is-flex is-align-items-center">
                        {% if oeuvre.fileName %}
                            <img class="img-galery has-max-height-80vh" src="{{ asset('/images/oeuvres/' ~ oeuvre.fileName) }}" alt="{{ oeuvre.fileName }}">
                        {% else %}
                            <img class="img-galery has-max-height-80vh" src="{{ asset('/build/images/480x320.86ac0bc4.png') }}" alt="Fichier image manquant">
                        {% endif %}
                    </figure>
                    <button class="modal-close is-large" aria-label="close" onclick="closeModal(this)"></button>
                </div>

                <div class="has-transition-5-ms column is-relative is-flex is-flex-direction-column is-justify-content-space-evenly is-align-items-center is-one-quarter-desktop is-half has-text-centered btn-for-display-popup is-hoverable-zoom-in">
                    <img src="{{ asset('images/oeuvres/' ~ oeuvre.fileName) | imagine_filter('small') }}" alt="">
                    <div class="tag">
                        {{ oeuvre.titre }}
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>

    <div class="column is-full is-flex is-justify-content-space-evenly">
        <a class="button is-small is-dark is-outlined mr-5" href="{{ path('year_directory_edit', {'id': year_directory.id}) }}">Modifier</a>

        {{ include('year_directory/_delete_form.html.twig') }}
    </div>

</div>
{% endblock %}